const DEFAULT_PLANS = [
  {
    slug: 'trial',
    name: 'Basic Trial Pack',
    description: '5hrs/month',
    price: 49.99,
    tokens: 500,
    hoursPerMonth: 5,
    bonusFeatures: [],
    marketingLabel: 'BASIC TRIAL PACK',
    marketingSummary: 'Perfect for trying out our services with minimal commitment.',
    marketingHighlight: 'Great for quick pilots and proof of concepts.',
    marketingFeatures: [
      'Limited hours ideal for testing',
      'Includes standard support',
      'Cancel anytime',
    ],
    isPopular: false,
  },
  {
    slug: 'starter',
    name: 'Starter',
    description: '20hrs/month',
    price: 99.99,
    tokens: 2000,
    hoursPerMonth: 20,
    bonusFeatures: [],
    marketingLabel: 'STARTER PACK',
    marketingSummary: 'Best for teams that are ready to scale with confidence.',
    marketingHighlight: 'Reliable capacity for growing operations.',
    marketingFeatures: [
      'Dedicated account specialist',
      'Faster response times',
      'Weekly reporting',
    ],
    isPopular: false,
  },
  {
    slug: 'fulltime',
    name: 'Full Time',
    description: '160hrs/month (Bonus: Weekend Support)',
    price: 3000,
    tokens: 10000,
    hoursPerMonth: 160,
    bonusFeatures: ['Weekend Support'],
    marketingLabel: 'FULL TIME',
    marketingSummary: 'Premium capacity with weekend coverage and premium SLAs.',
    marketingHighlight: 'Complete coverage for mission-critical workloads.',
    marketingFeatures: [
      'Weekend support included',
      'Premium success manager',
      'Custom workflows and QA',
    ],
    isPopular: true,
  },
  {
    slug: 'loadcash',
    name: 'Load Cash Minimum',
    description: 'Minimum (2hrs)',
    price: 50,
    tokens: 200,
    hoursPerMonth: 2,
    bonusFeatures: [],
    marketingLabel: 'LOAD CASH MINIMUM',
    marketingSummary: 'Flexible minimum load with on-demand access.',
    marketingHighlight: 'Pay-as-you-go flexibility.',
    marketingFeatures: [
      'Use balance anytime',
      'Perfect for ad-hoc tasks',
      'No expiration for unused hours',
    ],
    isPopular: false,
  },
];

module.exports = { DEFAULT_PLANS };
